package solutions;

/*
 * Problem:
 * 	Each new term in the Fibonacci sequence is generated by adding 
 * 	the previous two terms. By starting with 1 and 2, the first 10 
 * 	terms will be:
 * 
 * 	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * 	By considering the terms in the Fibonacci sequence whose values 
 * 	do not exceed four million, find the sum of the even-valued terms.
 * 
 * Answer: 4613732
 */
public class Problem2 {
	
	private static final double GOLDEN_RATIO = (1 + Math.sqrt(5)) / 2;
	private static final int UPPER_LIMIT = 4000000;
	
	public static void main(String[] args) {
		double multiplier = Math.pow(GOLDEN_RATIO, 3);
		long fib_val = 2, sum = 0;
		
		while (fib_val < UPPER_LIMIT) {
			sum += fib_val;
			fib_val = Math.round(fib_val * multiplier);
		}
		
		System.out.println(sum);
	}
}