;Each new term in the Fibonacci sequence is generated by adding
;the previous two terms. By starting with 1 and 2, the first 10
;terms will be:

;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;By considering the terms in the Fibonacci sequence whose values
;do not exceed four million, find the sum of the even-valued terms.

;==> 4613732
(ns clojure-euler.problem2)

(def golden_ratio (/ (+ 1 (Math/pow 5 0.5)) 2))
(def multiplier (Math/pow golden_ratio 3))
(defn solve-problem2 []
  (reduce + (take-while #(< % 4000000N)
                        (iterate #(Math/round (* % multiplier)) 2))))
