# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms. By starting with 1 and 2, the first 10
# terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.
#
# ==> 4613732

GOLDEN_RATIO = (1 + 5**0.5) / 2
multiplier = GOLDEN_RATIO**3
fib_val = 2
total = 0
while fib_val < 4000000 do
  total += fib_val
  fib_val = (fib_val * multiplier).round
end
puts total.to_i
